name: format check

on:
  push:
    tags: ["*"]
  pull_request:
    types: [ready_for_review, opened, reopened, auto_merge_enabled]
  merge_group:
    types: [checks_requested]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: "yarn"

      - name: Install dependencies (if not cached)
        run: yarn install --frozen-lockfile

      - name: Format check
        run: yarn lint
